image: node:15

stages:
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/

before_script:
  - npm ci --cache .npm --prefer-offline

validate_doc:
  stage: test
  script:
    - npm exec -- bump deploy --dry-run bump.openapi.v3.yml
  only:
    - branches
  except:
    - master

deploy_doc:
  stage: deploy
  script:
    - npm exec -- bump deploy bump.openapi.v3.yml
  only:
    - master
