language: node_js
node_js:
  - 15

jobs:
  include:
    - if: type = pull_request OR branch != master
      script: npm exec -- bump deploy --dry-run bump.openapi.v3.yml
    - if: type = push AND branch = master
      script: npm exec -- bump deploy bump.openapi.v3.yml
