version: '2.1'
orbs:
  node: circleci/node@4.4.0
jobs:
  validate-or-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-npm: false
      - run: npm install -g bump-cli
      - when:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - deploy:
                name: Deploy bump documentation
                command: npm exec -- bump deploy bump.openapi.v3.yml
      - unless:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Validate documentation
                command: npm exec -- bump deploy --dry-run bump.openapi.v3.yml
workflows:
  bump_workflow:
    jobs:
      - validate-or-deploy
