on:
  push:
    branches-ignore:
      - master

jobs:
  dry-run:
    runs-on: ubuntu-latest
    name: Dry-run an API doc deployment
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dry-run deployment on bump
      id: dry-run
      uses: bump-sh/github-action@0.3
      with:
        doc: ${{ secrets.doc_id }}
        token: ${{ secrets.doc_token }}
        file: bump.openapi.v3.yml
        command: dry-run
