on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Validate API doc
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy on Bump
      id: deploy
      uses: bump-sh/github-action@rename-id-into-doc
      with:
        doc: ${{ secrets.doc_id }}
        token: ${{ secrets.doc_token }}
        file: bump.openapi.v3.yml
        command: validate
